### ISSUE TITLE
URL endpoints

### ISSUE THREAD

**Issue by anhphamduy** [reactjs/vi.reactjs.org#6]
Should we keep all the url endpoints the same or change them as we translate?

For example, the current endpoint for tutorial is `/tutorial`. Do we change it to something like `/hướng-dẫn` or just leave it as it is?

**Comment by ltmylinh** [comment]
I think we should keep it as English. Don't need to translate endpoints.

**Comment by tesseralis** [comment]
Yes, keep it in English! Same goes for anchor links (`tutorial#overview`).

See here: https://github.com/reactjs/reactjs.org-translation/blob/master/style-guide.md
